# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smartcloud}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["yan"]
  s.date = %q{2011-07-12}
  s.description = %q{IBM SmartCloud API Gem}
  s.email = %q{yan.pritzker@cohesiveft.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/config/config.yml",
     "lib/hash_fix.rb",
     "lib/mime-types-1.16/History.txt",
     "lib/mime-types-1.16/Install.txt",
     "lib/mime-types-1.16/Licence.txt",
     "lib/mime-types-1.16/Manifest.txt",
     "lib/mime-types-1.16/README.txt",
     "lib/mime-types-1.16/Rakefile",
     "lib/mime-types-1.16/lib/mime/types.rb",
     "lib/mime-types-1.16/lib/mime/types.rb.data",
     "lib/mime-types-1.16/mime-types.gemspec",
     "lib/mime-types-1.16/setup.rb",
     "lib/mime-types-1.16/test/test_mime_type.rb",
     "lib/mime-types-1.16/test/test_mime_types.rb",
     "lib/mock_smartcloud.rb",
     "lib/rest-client-1.6.3/README.rdoc",
     "lib/rest-client-1.6.3/Rakefile",
     "lib/rest-client-1.6.3/VERSION",
     "lib/rest-client-1.6.3/bin/restclient",
     "lib/rest-client-1.6.3/history.md",
     "lib/rest-client-1.6.3/lib/rest-client.rb",
     "lib/rest-client-1.6.3/lib/rest_client.rb",
     "lib/rest-client-1.6.3/lib/restclient.rb",
     "lib/rest-client-1.6.3/lib/restclient/abstract_response.rb",
     "lib/rest-client-1.6.3/lib/restclient/exceptions.rb",
     "lib/rest-client-1.6.3/lib/restclient/net_http_ext.rb",
     "lib/rest-client-1.6.3/lib/restclient/payload.rb",
     "lib/rest-client-1.6.3/lib/restclient/raw_response.rb",
     "lib/rest-client-1.6.3/lib/restclient/request.rb",
     "lib/rest-client-1.6.3/lib/restclient/resource.rb",
     "lib/rest-client-1.6.3/lib/restclient/response.rb",
     "lib/restclient_fix.rb",
     "lib/smartcloud.rb",
     "lib/xml-simple-1.0.12/lib/xmlsimple.rb",
     "smartcloud",
     "smartcloud.gemspec",
     "test/helper.rb"
  ]
  s.homepage = %q{http://github.com/cohesive/smartcloud}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{IBM SmartCloud API Gem}
  s.test_files = [
    "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

